title: Mi Wiki
description: Documentación del sitio lab36.com.ar
theme: just-the-docs
url: https://lab36.com.ar
baseurl: ""  # Dejar vacío si es dominio raíz

# Opcional: navegación personalizada
just_the_docs:
  search_enabled: true
  logo: "/lab36logo.png"
